// Code generated by "stringer -type=Brand"; DO NOT EDIT.

package car

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[BMW-1]
	_ = x[Mercedes-2]
	_ = x[Audi-3]
	_ = x[Toyota-4]
	_ = x[Volkswagen-5]
	_ = x[Porsche-6]
	_ = x[Ferrari-7]
}

const _Brand_name = "UnknownBMWMercedesAudiToyotaVolkswagenPorscheFerrari"

var _Brand_index = [...]uint8{0, 7, 10, 18, 22, 28, 38, 45, 52}

func (i Brand) String() string {
	if i < 0 || i >= Brand(len(_Brand_index)-1) {
		return "Brand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Brand_name[_Brand_index[i]:_Brand_index[i+1]]
}
